### ISSUE TITLE
Convert "for" flow control from Go Template syntax to Ansible Playbook Syntax

### ISSUE THREAD

**Issue by ryandgoulding** [redhat-nfvpe/helm-ansible-template-exporter#4]
Helm Charts use an extended Go Template Engine implementation to parse template files.  Go templating uses the following syntax to represent for loops:
`
{{- range .Values.ingress.hosts }}
.someHostProperty
{{ end }}
`
There are a few important notes:
1) "end" is generic, and is the same as the conditional flow control end statement.  Since these can be nested, we need to be able to correctly associate the "end" tag in order to perform proper translation.
2) An iterator is implied, and you can reference attributes of the iterator using the member access "." operator.

The corresponding syntax in Jinja2 is something like this:
`
{% if ingress.enabled %}
{% for secret in ingress.secrets %}
apiVersion: v1
kind: Secret
metadata:
  name: fullname
  labels: labels
type: kubernetes.io/tls
data:
  tls.crt: {{ secret.certificate | b64encode }}
  tls.key: {{ secret.key | b64encode }}
---
{% endfor %}
{% endif %}
`
This example demonstrates:
1) for-each conversion
2) qualification of member access such as "secret.key"

This issue should also consider the for key/value conversion.  This will look more like this in Jinja2:
`
{%- for key, value in ingress.annotations.iteritems() %}
    {{ key }}: {{ value | quote }}
{%- endfor %}
`

**Comment by aneeshkp** [comment]
TDD- how to handle different for loops ... 
Data
---------------------------------------------------------

```

var chartName="testChart"
var Values=`
       ports1:  <-- this is list for items  in ports 
          - name: http
             externalPort: 80
             internalPort: 8080
          - name: management
            externalPort: 81
            internalPort: 8081
      ports2:   -<-- This is hash map , range with key values
           http:
              externalPort: 80
               internalPort: 8080
          management:
               externalPort: 81
             internalPort: 8081
`
```
# using ports1 which is a list 

``` 
var helmSimpleRange=`
			{{- range ports1 }}
			- {{ . | .name | quote }}
                        - {{ . | .chartName }}  <-- this global variable from values 
			- {{ . | .externalPort  }}
			- {{ . | .internalPort  }}
			{{- end }}`

var expectedSimpleLoop=`
			{% for item in ports1 %}
			- {{ . | $item.name | quote }}
                        - {{ . | .chartName }}   <-- this global variable from values 
			- {{ . | $item.externalPort  }}
			- {{ . | $item.internalPort  }}
			{% endfor %}`

```
```
var helmTupleRange=`
			{{- range tuple "config1.toml" "config2.toml" "config3.toml" }}
  			{{ . }}: |-
			{{ .chartName}} <-- this global variable from values 
  			{{- end }}`
var expectedTupleLoop=`
				{% for items in "config1.toml" "config2.toml" "config3.toml" %}
				{{ $items }}: |-
				{{ .chartName}} <-- this global variable from values 
				{%endfor%}`
```
# using ports2 which is a lmap
```
var helmDictRange=`
			{{- range $key, $value ports2 }}
			- port: {{ $value.externalPort }}
  			targetPort: {{ $value.internalPort }}
			chartName: {{,chartName}}
  			name: {{ $key }}
			{{- end }}`


var expectedDictLoop=`
			{%for $key, $value in ports }}
			- port: {{ $value.externalPort }}
  			targetPort: {{ $value.internalPort }}
			chartName: {{ .chartName }}    <-- this global variable from values 
                        name: {{ $key }}
			{% endfor%}`

```
